SELECT A.* 
 ,GET_CONTRACT(A.CITY,A.STREET,A.BON_BUN,A.BU_BUN,A.DAN_GI_MYEONG,A.SQUARE_METER,A.LAYER,A.CONSTRUCTION_DATE) AS CONTRACT 
 ,GET_TRANSACTIONCOUNT_LIST(A.CITY,A.STREET,A.BON_BUN,A.BU_BUN,A.DAN_GI_MYEONG,A.SQUARE_METER,A.LAYER,A.CONSTRUCTION_DATE) AS TRANSACTIONCOUNTLIST 
 FROM( 
  SELECT ROW_NUMBER() OVER (ORDER BY CONTRACT_DATE DESC, LPAD(CONTRACT_DAY, 2, '0') DESC) NO 
 ,ROW_NUMBER() OVER (PARTITION BY A.CITY ,A.STREET ,A.BON_BUN ,A.BU_BUN ,A.DAN_GI_MYEONG ,A.SQUARE_METER ,A.LAYER ,A.CONSTRUCTION_DATE ORDER BY A.CONTRACT_DATE DESC) AS RN  
 ,A.* FROM APT A 
  WHERE 1 = 1
  AND CONTRACT_DATE||LPAD(CONTRACT_DAY, 2, '0') BETWEEN REPLACE('2023-01-01','-','') AND REPLACE('2023-02-10','-','') 
  AND CITY  LIKE '%'||REPLACE('부산광역시','전체','')||'%'||'%'||REPLACE('기장군','전체','')||'%'||'%'||REPLACE('정관읍','전체','')||'%' 
  AND TO_NUMBER(SUBSTR(SQUARE_METER, 1, INSTR(SQUARE_METER, '.') - 1))  BETWEEN  TO_NUMBER('0')  AND  TO_NUMBER('10000')
  AND  TO_NUMBER(REPLACE(AMOUNT, ',')) BETWEEN  TO_NUMBER(REPLACE('0', ','))  AND  TO_NUMBER(REPLACE('100000000', ','))
  ORDER BY CONTRACT_DATE DESC, LPAD(CONTRACT_DAY, 2, '0') DESC 
) A 
WHERE A.NO BETWEEN '1' AND '9' 
AND A.RN= 1 ;


SELECT * FROM (
SELECT A.* 
 ,ROW_NUMBER() OVER (ORDER BY CONTRACT_DATE DESC, LPAD(CONTRACT_DAY, 2, '0') DESC) NO 
 ,GET_CONTRACT(A.CITY,A.STREET,A.BON_BUN,A.BU_BUN,A.DAN_GI_MYEONG,A.SQUARE_METER,A.LAYER,A.CONSTRUCTION_DATE) AS CONTRACT 
 ,GET_TRANSACTIONCOUNT_LIST(A.CITY,A.STREET,A.BON_BUN,A.BU_BUN,A.DAN_GI_MYEONG,A.SQUARE_METER,A.LAYER,A.CONSTRUCTION_DATE) AS TRANSACTIONCOUNTLIST 
 FROM( 
  SELECT 
 ROW_NUMBER() OVER (PARTITION BY A.CITY ,A.STREET ,A.BON_BUN ,A.BU_BUN ,A.DAN_GI_MYEONG ,A.SQUARE_METER ,A.LAYER ,A.CONSTRUCTION_DATE ORDER BY A.CONTRACT_DATE DESC) AS RN  
 ,A.* FROM APT A 
  WHERE 1 = 1
  AND CONTRACT_DATE||LPAD(CONTRACT_DAY, 2, '0') BETWEEN REPLACE('2023-01-01','-','') AND REPLACE('2023-02-10','-','') 
  AND CITY  LIKE '%'||REPLACE('부산광역시','전체','')||'%'||'%'||REPLACE('기장군','전체','')||'%'||'%'||REPLACE('정관읍','전체','')||'%' 
  AND TO_NUMBER(SUBSTR(SQUARE_METER, 1, INSTR(SQUARE_METER, '.') - 1))  BETWEEN  TO_NUMBER('0')  AND  TO_NUMBER('10000')
  AND  TO_NUMBER(REPLACE(AMOUNT, ',')) BETWEEN  TO_NUMBER(REPLACE('0', ','))  AND  TO_NUMBER(REPLACE('100000000', ','))
  ORDER BY CONTRACT_DATE DESC, LPAD(CONTRACT_DAY, 2, '0') DESC 
) A 
WHERE A.RN= 1 
)

;



   SELECT count(*) FROM( 
       SELECT 
       ROW_NUMBER() OVER (PARTITION BY A.CITY ,A.STREET ,A.BON_BUN ,A.BU_BUN ,A.DAN_GI_MYEONG ,A.SQUARE_METER ,A.LAYER ,A.CONSTRUCTION_DATE ORDER BY A.CONTRACT_DATE DESC) AS RN  
       FROM APT A 
       WHERE 1 = 1
       AND CONTRACT_DATE||LPAD(CONTRACT_DAY, 2, '0') BETWEEN REPLACE('2023-01-01','-','') AND REPLACE('2023-02-10','-','') 
       AND CITY  LIKE '%'||REPLACE('부산광역시','전체','')||'%'||'%'||REPLACE('기장군','전체','')||'%'||'%'||REPLACE('정관읍','전체','')||'%' 
--       AND TO_NUMBER(REPLACE(SQUARE_METER, '.')) BETWEEN  TO_NUMBER('0')  AND  TO_NUMBER('10000')
       AND  TO_NUMBER(REPLACE(AMOUNT, ',')) BETWEEN  TO_NUMBER(REPLACE('0', ','))  AND  TO_NUMBER(REPLACE('100000000', ','))
       
--         AND CONTRACT_DATE||LPAD(CONTRACT_DAY, 2, '0') BETWEEN REPLACE('2023-01-01','-','') AND REPLACE('2023-02-10','-','') 
--          AND CITY  LIKE '%'||REPLACE('부산광역시','전체','')||'%'||'%'||REPLACE('기장군','전체','')||'%'||'%'||REPLACE('정관읍','전체','')||'%' 
          AND TO_NUMBER(SUBSTR(SQUARE_METER, 1, INSTR(SQUARE_METER, '.') - 1))  BETWEEN  TO_NUMBER('0')  AND  TO_NUMBER('10000')
--          AND  TO_NUMBER(REPLACE(AMOUNT, ',')) BETWEEN  TO_NUMBER(REPLACE('0', ','))  AND  TO_NUMBER(REPLACE('100000000', ','))
       
     ) A 
     WHERE A.RN= 1 
     ;
