--------------------------------------------------------
--  DDL for Table APT
--------------------------------------------------------

  CREATE TABLE "C##MYHOME"."APT" 
   (	"APT_ID" NUMBER, 
	"CITY" VARCHAR2(100 BYTE), 
	"STREET" VARCHAR2(50 BYTE), 
	"BON_BUN" VARCHAR2(50 BYTE), 
	"BU_BUN" VARCHAR2(50 BYTE), 
	"DAN_GI_MYEONG" VARCHAR2(100 BYTE), 
	"SQUARE_METER" VARCHAR2(50 BYTE), 
	"CONTRACT_DATE" VARCHAR2(50 BYTE), 
	"CONTRACT_DAY" VARCHAR2(50 BYTE), 
	"AMOUNT" VARCHAR2(50 BYTE), 
	"LAYER" VARCHAR2(50 BYTE), 
	"CONSTRUCTION_DATE" VARCHAR2(50 BYTE), 
	"ROAD_NAME" VARCHAR2(50 BYTE), 
	"REASON_CANCELLATION_DATE" VARCHAR2(50 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(50 BYTE), 
	"LOCATION_AGENCY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##MYHOME"."APT"."APT_ID" IS 'PK_시퀀스';
   COMMENT ON COLUMN "C##MYHOME"."APT"."CITY" IS '시군구';
   COMMENT ON COLUMN "C##MYHOME"."APT"."STREET" IS '번지';
   COMMENT ON COLUMN "C##MYHOME"."APT"."BON_BUN" IS '본번';
   COMMENT ON COLUMN "C##MYHOME"."APT"."BU_BUN" IS '부번';
   COMMENT ON COLUMN "C##MYHOME"."APT"."DAN_GI_MYEONG" IS '단지명';
   COMMENT ON COLUMN "C##MYHOME"."APT"."SQUARE_METER" IS '전용면적(㎡)';
   COMMENT ON COLUMN "C##MYHOME"."APT"."CONTRACT_DATE" IS '계약년월';
   COMMENT ON COLUMN "C##MYHOME"."APT"."CONTRACT_DAY" IS '계약일';
   COMMENT ON COLUMN "C##MYHOME"."APT"."AMOUNT" IS '거래금액(만원)';
   COMMENT ON COLUMN "C##MYHOME"."APT"."LAYER" IS '층';
   COMMENT ON COLUMN "C##MYHOME"."APT"."CONSTRUCTION_DATE" IS '건축년도';
   COMMENT ON COLUMN "C##MYHOME"."APT"."ROAD_NAME" IS '도로명';
   COMMENT ON COLUMN "C##MYHOME"."APT"."REASON_CANCELLATION_DATE" IS '해제사유발생일';
   COMMENT ON COLUMN "C##MYHOME"."APT"."TRANSACTION_TYPE" IS '거래유형';
   COMMENT ON COLUMN "C##MYHOME"."APT"."LOCATION_AGENCY" IS '중개사소재지';
--------------------------------------------------------
--  DDL for Table APT_TEST
--------------------------------------------------------

  CREATE TABLE "C##MYHOME"."APT_TEST" 
   (	"CITY" VARCHAR2(100 BYTE), 
	"STREET" VARCHAR2(50 BYTE), 
	"BON_BUN" VARCHAR2(50 BYTE), 
	"BU_BUN" VARCHAR2(50 BYTE), 
	"DAN_GI_MYEONG" VARCHAR2(100 BYTE), 
	"SQUARE_METER" VARCHAR2(50 BYTE), 
	"CONTRACT_DATE" VARCHAR2(50 BYTE), 
	"CONTRACT_DAY" VARCHAR2(50 BYTE), 
	"AMOUNT" VARCHAR2(50 BYTE), 
	"LAYER" VARCHAR2(50 BYTE), 
	"CONSTRUCTION_DATE" VARCHAR2(50 BYTE), 
	"ROAD_NAME" VARCHAR2(200 BYTE), 
	"REASON_CANCELLATION_DATE" VARCHAR2(50 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(50 BYTE), 
	"LOCATION_AGENCY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MYHOME"."TABLE1_PK" ON "C##MYHOME"."APT" ("APT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APT
--------------------------------------------------------

  ALTER TABLE "C##MYHOME"."APT" MODIFY ("APT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MYHOME"."APT" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("APT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
